title: 慢摇哥哥的博客
description: 数据科学和产品设计
meta_description: "数据科学、产品设计、云和效率"

baseurl: ''
abouturl: about.html
permalink: /:title:output_ext

markdown: kramdown
highlighter: pygments
logo: false
paginate: 10
domain_name: 'aaronyao.github.io'
google_analytics: 'UA-135953860-1'
plugins: [jekyll-paginate]

# Auth info
author: 'Aaron Yao'

# For development
host: 0.0.0.0
port: 80
