name: 慢摇哥哥的博客
description: 云、数据科学、产品设计、和效率
meta_description: "云、数据科学、产品设计、和效率"

baseurl: ''
abouturl: about.html
permalink: /:title:output_ext

markdown: kramdown
highlighter: pygments
logo: false
paginate: 4
domain_name: 'aaronyao.github.io'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Share
social-share: true
social-share-items: ['wechat', 'weibo', 'douban', 'twitter']

# Details for the RSS feed generator
url:            'https://'
author:         '姚关伟'

